const ShopActionTypes = {
  FETCH_COLLECTIONS_START: "FETCH_COLLECTIONS_START",
  FETCH_COLLECTIONS_SUCCESS: "FETCH_COLLECTIONS_SUCCESS",
  FETCH_COLLECTIONS_FAILURE: "FETCH_COLLECTIONS_FAILURE",
  FETCH_SEARCHED_ELEMENTS_START: "FETCH_SEARCHED_ELEMENTS_START"
};

export default ShopActionTypes;
