const RecentlyAddedItemsActionTypes = {
  SET_RECENTLY_ADDED_ITEM: "SET_RECENTLY_ADDED_ITEM",
  REMOVE_RECENTLY_ADDED_ITEM: "REMOVE_RECENTLY_ADDED_ITEM",

  TOGGLE_VISIBILITY: "TOGGLE_VISIBILITY"
};

export default RecentlyAddedItemsActionTypes;
